# Week 9

Intro to ML using Linear Regressions

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
tdf = pd.read_csv("data9_tips.csv")
tdf.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [9]:
import patsy as pts

In [11]:
y,x = pts.dmatrices('tip ~ total_bill + size + C(time)', data = tdf, return_type = 'dataframe')
x.head()

   Intercept  C(time)[T.Lunch]  total_bill  size
0        1.0               0.0       16.99   2.0
1        1.0               0.0       10.34   3.0
2        1.0               0.0       21.01   3.0
3        1.0               0.0       23.68   2.0
4        1.0               0.0       24.59   4.0

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.5, random_state = 10101)

In [15]:
from sklearn.linear_model import LinearRegression

In [17]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [19]:
model.intercept_

array([0.474574])

In [21]:
model.coef_

array([[0.        , 0.12728049, 0.09671437, 0.19601929]])

In [31]:
print(f"Tip = {model.intercept_[0]:.3f} + " +
      f"{model.coef_[0][1]:.3f} Lunch + " +
      f"{model.coef_[0][2]:.3f} Total Bill + " +
      f"{model.coef_[0][3]:.3f} Size")

Tip = 0.475 + 0.127 Lunch + 0.097 Total Bill + 0.196 Size

In [25]:
results = model.predict(x_test)
results.shape

(122, 1)

In [27]:
y_test.shape

(122, 1)

In [29]:
score = model.score(x_test, y_test)
print (f"LR model score = {score: .3f}")

LR model score =  0.454

In [33]:
import statsmodels.formula.api as smf

result = smf.ols(formula = 'tip ~ total_bill + size + C(time)', data = tdf).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.468
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                     70.34
Date:                Mon, 24 Mar 2025   Prob (F-statistic):           1.13e-32
Time:                        14:07:15   Log-Likelihood:                -347.98
No. Observations:                 244   AIC:                             704.0
Df Residuals:                     240   BIC:                             718.0
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            0.6671      0.205      3.249      0.001       0.263       1.072
C(time)[T.Lunch]     0.0041      0.148      0.028      0.978      -0.286       0.295
total_bill           0.0928      0.009     10.037      0.000       0.075       0.111
size                 0.1926      0.085      2.253      0.025       0.024       0.361
==============================================================================
Omnibus:                       24.790   Durbin-Watson:                   2.100
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               46.226
Skew:                           0.546   Prob(JB):                     9.17e-11
Kurtosis:                       4.831   Cond. No.                         73.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""